# Generated by Django 5.1 on 2024-08-09 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0003_delete_pago_delete_tipopagos'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateTimeField(auto_now=True)),
                ('monto', models.FloatField()),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.servicio')),
                ('tipo_pagos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzas.tipopagos')),
            ],
        ),
    ]
